---
ciliumLbIpam:
  pools:
    - name: b-lb-pool
      labels:
        app.kubernetes.io/name: cilium-lb-ipam
        app.kubernetes.io/part-of: scalex-repo-poc
        org.ulagbulag.io/cluster: b
      spec:
        blocks:
          - start: 10.33.142.1
            stop: 10.33.142.254
        serviceSelector:
          matchLabels: {}
  l2AnnouncementPolicies:
    - name: b-l2-policy
      labels:
        app.kubernetes.io/name: cilium-lb-ipam
        app.kubernetes.io/part-of: scalex-repo-poc
        org.ulagbulag.io/cluster: b
      spec:
        loadBalancerIPs: true
        serviceSelector:
          matchLabels: {}
