apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: scalex-poc-bucket
  namespace: csi-rook-ceph
  labels:
    app.kubernetes.io/name: scalex-poc-rgw
    app.kubernetes.io/part-of: scalex-federation-poc
    scalex.io/infra-owner: b-k8s
spec:
  bucketName: scalex-poc
  storageClassName: ceph-bucket
