apiVersion: v1
kind: Service
metadata:
  name: scalex-poc-rgw
  namespace: csi-rook-ceph
  labels:
    app.kubernetes.io/name: scalex-poc-rgw
    app.kubernetes.io/part-of: scalex-federation-poc
    scalex.io/infra-owner: b-k8s
  annotations:
    lbipam.cilium.io/ips: 10.33.142.10
spec:
  type: LoadBalancer
  selector:
    app: rook-ceph-rgw
    rook_cluster: csi-rook-ceph
    rook_object_store: scalex-poc
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
