---
expose:
  type: loadBalancer

  tls:
    enabled: false

  loadBalancer:
    name: harbor
    annotations:
      lbipam.cilium.io/ips: "10.33.142.25"
    ports:
      httpPort: 80
    sourceRanges: []

externalURL: http://10.33.142.25

enableMigrateHelmHook: false
